version: '3.3'

services:
  mongo:
    image: mongo
    container_name: book_db
    ports:
      - 2717:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootPassword
      - MONGO_INITDB_DATABASE=cscl
      - DB_USER=cscl
      - DB_PASS=mongo # Please note that password must match value in 'seed/1_initialize_user.js'
    volumes:
      - mongodb_data:/data/db
      - ./mongo/seed/:/docker-entrypoint-initdb.d/:ro
  node:
    image: "node:12"
    container_name: book_server
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./server:/home/node/app
    ports:
      - 3000:3000
    links:
      - "mongo:database"
    command: "npm start"
    
  react:
    container_name: docker_client
    build:
      context: ./client/
      dockerfile: Dockerfile
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - './client:/app'
      - '/app/node_modules'
    ports:
      - 8000:8000

volumes:
  mongodb_data:
    driver_opts:
      type: none
      device: /Users/jarry/Git/caffe-library/mongo/mongodb_data
      o: bind
